name    'mtaylor-sshkeypair'
version '0.1.0'
source ''
author 'mtaylor@redhat.com'
license 'GPLv3+'
summary 'PuppetSSH configuration for Foreman Smart Proxy '
description 'Module for configuring the PuppetSSh in the Foreman Smart Proxy service'
project_page 'http://github.com/theforeman/foreman-installer'

## dependencies
dependency 'maestrodev/ssh_keygen', '>= 1.1.0'
dependency 'puppetlabs/stdlib', '>= 2.0.0'

